codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        target: auto  # Let Codecov determine baseline automatically
        threshold: 1% # Allow small drops without failing
        base: auto
        if_not_found: success
    patch:
      default:
        target: 80%   # Expect good coverage on new code
        threshold: 0%
        if_not_found: success

  ignore:
    - "**/mocks/**"
    - "**/tests/**"
    - "**/vendor/**"
    - "**/*.pb.go"   # Ignore generated protobuf files

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true  # Don't comment if coverage hasn't changed

component_management:
  default_rules:  # default rules that will be inherited by all components
    statuses:
      - type: project # in this case every component that doens't have a status defined will have a project type one
        target: auto
        branches:
          - "!main"
  individual_components:
    - component_id: types  # this is an identifier that should not be changed
      name: types  # this is a display name, and can be changed freely
      paths:
        - types/**
    - component_id: messages_authorizes  # this is an identifier that should not be changed
      name: authorizes  # this is a display name, and can be changed freely
      paths:
        - authorizes/**

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: true
      macro: false

flags:
  unit:
    paths:
      - ./...
    carryforward: true

github_checks:
  annotations: true

