name: Benchmark

on:
  workflow_dispatch:

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - authorize
          # - bootnotification
          # - cancelreservation
        go-version:
          - "stable"
          - "1.23"
          - "1.24"

    name: "${{ matrix.module }} Benchmarks (Go ${{ matrix.go-version }})"
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Run main benchmarks
        run: |
          mkdir -p ${{ matrix.go-version }}
          go test -bench=. -benchmem ./messages/${{ matrix.module }}/benchmarks       >${{ matrix.go-version }}/${{ matrix.module }}-benchmarks.txt

      - name: Run types benchmarks
        run: |
          mkdir -p ${{ matrix.go-version }}
          go test -bench=. -benchmem ./messages/${{ matrix.module }}/types/benchmarks >${{ matrix.go-version }}/${{ matrix.module }}-types-benchmarks.txt

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory structure
        run: tree -a -L 3

      - name: Process Benchmarks of ${{ matrix.module }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          benchmark-data-dir-path:  ${{ matrix.go-version }}/${{ matrix.module }}-benchmarks
          name:                     Go Benchmark (${{ matrix.module }} - Go ${{ matrix.go-version }})
          output-file-path:         ${{ matrix.go-version }}/${{ matrix.module }}-benchmarks.txt
          github-token:             ${{ secrets.GITHUB_TOKEN }}
          summary-always:           true
          tool:                     go
          auto-push:                true

      - name: Process Benchmarks of ${{ matrix.module }} types
        uses: benchmark-action/github-action-benchmark@v1
        with:
          benchmark-data-dir-path:  ${{ matrix.go-version }}/${{ matrix.module }}-types-benchmarks
          name:                     Go Benchmark (${{ matrix.module }} - Go ${{ matrix.go-version }})
          output-file-path:         ${{ matrix.go-version }}/${{ matrix.module }}-types-benchmarks.txt
          github-token:             ${{ secrets.GITHUB_TOKEN }}
          summary-always:           true
          tool:                     go
          auto-push:                true

