name: Benchmark

on:
  workflow_dispatch:
  pull_request_target:
  push:
    tags:
      - v*

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - authorize
          - bootnotification

    name: "${{ matrix.module }} Benchmarks"
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Run main benchmarks
        run: |
          go test -bench=. -benchmem ./messages/${{ matrix.module }}/benchmarks >${{ matrix.module }}-benchmarks.txt

      - name: Run types benchmarks
        run: |
          go test -bench=. -benchmem ./messages/${{ matrix.module }}/types/benchmarks >${{ matrix.module }}-types-benchmarks.txt

      - name: Publish main benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark (${{ matrix.module }})
          tool: go
          output-file-path: ${{ matrix.module }}-benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: ${{ matrix.module }}-benchmarks
          gh-pages-branch: gh-pages

      - name: Publish types benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark (${{ matrix.module }}-types)
          tool: go
          output-file-path: ${{ matrix.module }}-types-benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: ${{ matrix.module }}-types-benchmarks
          gh-pages-branch: gh-pages
