name: Benchmark

on:
  workflow_dispatch:

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - "stable"
          - "1.23"
          - "1.24"

    name: "Benchmarks (Go ${{ matrix.go-version }})"
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: false

      - name: Run main benchmarks
        run: |
          mkdir -p ${{ matrix.go-version }}
          go test -bench=. -run=^$ ./... -benchtime 20s -benchmem  >${{ matrix.go-version }}/benchmarks.txt

      - name: Install tree
        run: sudo apt-get update && sudo apt-get install -y tree

      - name: Show directory structure
        run: tree -a -L 3

      - name: Process Benchmarks on ${{ matrix.go-version }}
        uses: benchmark-action/github-action-benchmark@v1
        with:
          benchmark-data-dir-path:  ${{ matrix.go-version }}/benchmarks
          name:                     Go Benchmark on ${{ matrix.go-version }})
          output-file-path:         ${{ matrix.go-version }}/benchmarks.txt
          github-token:             ${{ secrets.GITHUB_TOKEN }}
          summary-always:           true
          tool:                     go
          auto-push:                true
