name: Benchmark

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - authorize
          - bootnotification
        go-version: ["1.23", "1.24", "stable"]

    name: "${{ matrix.module }} Benchmarks (Go ${{ matrix.go-version }})"
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run main benchmarks
        run: |
          mkdir -p ${{ matrix.go-version }}
          go test -bench=. -benchmem ./messages/${{ matrix.module }}/benchmarks >${{ matrix.go-version }}/${{ matrix.module }}-benchmarks.txt

      - name: Run types benchmarks
        run: |
          mkdir -p ${{ matrix.go-version }}
          go test -bench=. -benchmem ./messages/${{ matrix.module }}/types/benchmarks >${{ matrix.go-version }}/${{ matrix.module }}-types-benchmarks.txt

      - name: Publish main benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark (${{ matrix.module }} - Go ${{ matrix.go-version }})
          tool: go
          output-file-path: ${{ matrix.go-version }}/${{ matrix.module }}-benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          benchmark-data-dir-path: ${{ matrix.go-version }}/${{ matrix.module }}-benchmarks
          gh-pages-branch: gh-pages

      - name: Publish types benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark (${{ matrix.module }}-types - Go ${{ matrix.go-version }})
          tool: go
          output-file-path: ${{ matrix.go-version }}/${{ matrix.module }}-types-benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          benchmark-data-dir-path: ${{ matrix.go-version }}/${{ matrix.module }}-types-benchmarks
          gh-pages-branch: gh-pages

      - name: Upload main benchmarks
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-${{ matrix.go-version }}-main
          path: ${{ matrix.go-version }}/${{ matrix.module }}-benchmarks.txt

      - name: Upload types benchmarks
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.module }}-${{ matrix.go-version }}-types
          path: ${{ matrix.go-version }}/${{ matrix.module }}-types-benchmarks.txt

  push-benchmarks:
    needs: run-benchmarks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
      - name: Download all benchmark artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./new-benchmarks
      - name: Copy new benchmark files to root
        run: |
          find ./new-benchmarks -type f -print0 | xargs -0 -I{} cp {} .
      - name: Set up git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit and push new benchmarks
        run: |
          git add .
          git commit -m "Update Go benchmark results [skip ci]" || echo "Nothing to commit"
          git push origin gh-pages
