name: Benchmark

on:
  workflow_dispatch:
  pull_request_target:
  push:
    tags:
      - v*

jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Run Go Benchmarks
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run benchmarks
        run: |
          go test -bench=. -benchmem ./... > benchmark-output.txt

      - name: Store and compare benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: go
          output-file-path: benchmark-output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: benchmark-data
          gh-pages-branch: gh-pages
