name: Benchmark

on:
  schedule:
    - cron: '0 8 * * 3' # Wednesday at 10:00am CET
  workflow_dispatch:
  pull_request_target:
  push:
    branches:
      - '**'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22, 1.23, 1.24] # Add more versions as needed
    name: Go ${{ matrix.go-version }} Benchmark
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run benchmarks
        run: |
          mkdir -p benchmarks
          go test -bench=. -benchmem ./... > "benchmarks/benchmark-${{ matrix.go-version }}.txt"

      - name: Store and compare benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark (Go ${{ matrix.go-version }})
          tool: 'go'
          output-file-path: "benchmarks/benchmark-${{ matrix.go-version }}.txt"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: "benchmark-data/${{ matrix.go-version }}"
          gh-pages-branch: gh-pages
