name: Benchmark

on:
  workflow_dispatch:
  pull_request_target:
  push:
    tags:
      - v*

jobs:
  benchmark:
    runs-on: ubuntu-latest
    name: Run Go Benchmarks
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24

      - name: Run Authorize Benchmarks
        run: |
          go test -bench=. -benchmem ./messages/authorize/benchmarks >authorize-benchmarks.txt

      - name: Publish Authorize Benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: go
          output-file-path: authorize-benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: authorize-benchmarks
          gh-pages-branch: gh-pages

      - name: Run Authorize Types Benchmarks
        run: |
          go test -bench=. -benchmem ./messages/authorize/types/benchmarks >authorize-types-benchmarks.txt

      - name: Publish Authorize Types Benchmarks
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Go Benchmark
          tool: go
          output-file-path: authorize-types-benchmarks.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          benchmark-data-dir-path: authorize-types-benchmarks
          gh-pages-branch: gh-pages
