name: Build

on:
  push:
    branches:
      - '**'

jobs:
  Unittest:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: false

      - run: mkdir -p reports

      - name: Execute test
        run: go test -mod=readonly -v -coverpkg=`go list -mod=readonly ./... | grep -v '/tests' | paste -sd ',' -` -coverprofile=reports/coverage.out -run '^Test' ./... >reports/test.txt

      - name: Coverage Percentage
        run: go tool cover -func=reports/coverage.out

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "Go test artifacts for build ${{ github.run_number }} in ocpp16messages"
          path: reports
          retention-days: 3
