name: Build

on:
  workflow_dispatch:

jobs:
  Unittest:
    name: Unittest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
          cache: false

      - run: mkdir -p reports

      - name: Execute test2
        run: go test -mod=readonly -v -coverpkg=`go list -mod=readonly ./... | grep -v '/tests' | paste -sd ',' -` -coverprofile=reports/coverage.out -run '^Test' ./... >reports/coverage.txt

      - run: cat reports/coverage.txt

      - name: Coverage Percentage
        run: echo "$(go tool cover -func=.reports/coverage.out | tail -1 | awk -F" " '{print $$NF}') covered"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "Go test artifacts for build ${{ github.run_number }} in ocpp16messages"
          path: reports
